ability to cache the stroke for reload later if user cancels or errors. TBA if this works for an error
where blender removes the contour_tools RNA  eg

ReferenceError: StructRNA of type CGCOOKIE_OT_retopo_contour has been removed